# ==============================================================================
# FAIL2BAN - JAIL POUR NGINX BAD BOTS
# Fichier : /etc/fail2ban/jail.d/nginx-bad-bots.conf
# ==============================================================================

[nginx-bad-bots]
enabled  = true
port     = http,https
filter   = nginx-bad-bots
logpath  = /var/log/nginx/odoo.access.log
maxretry = 3        # 3 tentatives suspectes = BAN
findtime = 300      # Dans une fenêtre de 5 minutes
bantime  = 7200     # Banni pour 2 heures
action   = iptables-multiport[name=nginx-bad-bots, port="http,https", protocol=tcp]
