# ==============================================================================
# FAIL2BAN - JAIL POUR NGINX BAD BOTS
# Fichier : /etc/fail2ban/jail.d/nginx-bad-bots.conf
# ==============================================================================

[nginx-meta-abuse]
enabled  = true
port     = http,https
filter   = nginx-meta-abuse
logpath  = /var/log/nginx/odoo.access.log
maxretry = 10
findtime = 300
bantime  = 8640000
action   = iptables-multiport[name=nginx-meta, port="http,https", protocol=tcp]

[nginx-bad-bots]
enabled  = true
port     = http,https
filter   = nginx-bad-bots
logpath  = /var/log/nginx/odoo.access.log
maxretry = 3
findtime = 300
bantime  = 8640000
action   = iptables-multiport[name=nginx-bad-bots, port="http,https", protocol=tcp]

[nginx-scanner]
enabled  = true
port     = http,https
filter   = nginx-scanner
logpath  = /var/log/nginx/odoo.access.log
maxretry = 10
findtime = 600
bantime  = 8640000
action   = iptables-multiport[name=nginx-scanner, port="http,https", protocol=tcp]
